export default {
  modelsOnly: {
    output: {
      mode: "split",
      target: "src/models", // folder to generate models/enums
      schemas: "src/models", // folder for schema definitions
      // clean: true, // removes old generated files
      indexFiles: true,
      override: {
        zod: {
          generateEachHttpStatus: true,
        },
        // This removes the version
        header: (info: any) => [`Generated by Orval`, `Do not edit manually.`, ...(info.title ? [info.title] : [])],
      },
    },
    input: {
      // Orval v8 validates input strictly; this local file is pre-sanitized by scripts/prepare-openapi.mjs.
      target: "./.orval/openapi.sanitized.json",
      filters: {
        tags: [/api/],
      },
    },
    outputOptions: {
      exportModels: true, // only generate components.schemas
      exportSchemas: false,
    },
    hooks: {
      afterAllFilesWrite: "prettier --write",
    },
    mock: false,
    override: {
      mutator: undefined,
      query: { useQuery: false },
      operations: {},
    },
  },
};
