/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { UserRole } from "./userRole";

export interface AccountDTO {
  id?: number;
  username?: string;
  email?: string;
  name?: string;
  phone?: string;
  image?: string;
  roles?: UserRole[];
}
