/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { GrantedAuthority } from "./grantedAuthority";

export interface Account {
  createdDate?: string;
  lastModifiedDate?: string;
  id?: number;
  username?: string;
  email?: string;
  authorities?: GrantedAuthority[];
}
