/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { GrantedAuthority } from "./grantedAuthority";

export interface Account {
  createdDate?: string;
  lastModifiedDate?: string;
  id?: number;
  username?: string;
  email?: string;
  authorities?: GrantedAuthority[];
}
