/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { Gender } from "./gender";
import type { UserRole } from "./userRole";

export interface AccountDetailDTO {
  id?: number;
  username?: string;
  image?: string;
  email?: string;
  roles?: UserRole[];
  name?: string;
  phone?: string;
  gender?: Gender;
  dob?: string;
  joinedDate?: string;
  totalFollows?: number;
  totalReviews?: number;
}
