/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { UserRole } from "./userRole";
import type { Gender } from "./gender";

export interface AccountDetailDTO {
  id?: number;
  username?: string;
  image?: string;
  email?: string;
  roles?: UserRole[];
  name?: string;
  phone?: string;
  gender?: Gender;
  dob?: string;
  joinedDate?: string;
  totalFollows?: number;
  totalReviews?: number;
}
