/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { Gender } from "./gender";

export interface AccountProfile {
  name?: string;
  phone?: string;
  gender?: Gender;
  dob?: string;
}
