/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { Gender } from "./gender";
import type { UserRole } from "./userRole";

export interface AccountRequest {
  /**
   * @minLength 4
   * @maxLength 24
   */
  username: string;
  /**
   * @minLength 8
   * @maxLength 24
   */
  pass?: string;
  email: string;
  roles: UserRole[];
  /**
   * @minLength 0
   * @maxLength 250
   */
  name?: string;
  /** @pattern \(?([0-9]{3})\)?([ .-]?)([0-9]{3})\2([0-9]{3}) */
  phone?: string;
  dob?: string;
  gender?: Gender;
  removeImage?: boolean;
}
