/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { Gender } from "./gender";

export interface AccountProfile {
  name?: string;
  phone?: string;
  gender?: Gender;
  dob?: string;
}
