/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { UserRole } from "./userRole";

export interface AccountDTO {
  id?: number;
  username?: string;
  email?: string;
  name?: string;
  phone?: string;
  image?: string;
  roles?: UserRole[];
}
