/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { AddressType } from "./addressType";

export interface Address {
  id?: number;
  name?: string;
  companyName?: string;
  phone?: string;
  address?: string;
  detail?: string;
  provinceId?: number;
  districtId?: number;
  wardCode?: string;
  type?: AddressType;
}
