/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { AddressType } from "./addressType";

export interface AddressRequest {
  /**
   * @minLength 0
   * @maxLength 250
   */
  name: string;
  /**
   * @minLength 0
   * @maxLength 250
   */
  companyName?: string;
  /** @pattern \(?([0-9]{3})\)?([ .-]?)([0-9]{3})\2([0-9]{3}) */
  phone: string;
  /**
   * @minLength 0
   * @maxLength 200
   */
  city: string;
  /**
   * @minLength 0
   * @maxLength 300
   */
  address: string;
  type?: AddressType;
  isDefault?: boolean;
}
