/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { AddressType } from "./addressType";

export interface Address {
  id?: number;
  name?: string;
  companyName?: string;
  phone?: string;
  city?: string;
  address?: string;
  type?: AddressType;
}
