/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export type AddressType = (typeof AddressType)[keyof typeof AddressType];

export const AddressType = {
  HOME: "HOME",
  OFFICE: "OFFICE",
} as const;
