/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */

export type AddressType = (typeof AddressType)[keyof typeof AddressType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddressType = {
  HOME: "HOME",
  OFFICE: "OFFICE",
} as const;
