/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { AddressType } from "./addressType";

export interface AddressRequest {
  /**
   * @minLength 0
   * @maxLength 250
   */
  name: string;
  /**
   * @minLength 0
   * @maxLength 250
   */
  companyName?: string;
  /** @pattern \(?([0-9]{4})\)?([ .-]?)([0-9]{3})\2([0-9]{3}) */
  phone: string;
  /**
   * @minLength 0
   * @maxLength 200
   */
  address: string;
  /**
   * @minLength 0
   * @maxLength 300
   */
  detail: string;
  provinceId: number;
  districtId: number;
  wardCode: string;
  type?: AddressType;
  isDefault?: boolean;
}
