/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface BannerRequest {
  /**
   * @minLength 5
   * @maxLength 200
   */
  name: string;
  /**
   * @minLength 0
   * @maxLength 4000
   */
  description?: string;
  url: string;
  shopId?: number;
}
