/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { BannerDTOSrcSet } from "./bannerDTOSrcSet";

export interface BannerDTO {
  id?: number;
  shopId?: number;
  name?: string;
  description?: string;
  srcSet?: BannerDTOSrcSet;
  url?: string;
}
