/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { BannerDTOSrcSet } from "./bannerDTOSrcSet";

export interface BannerDTO {
  id?: number;
  shopId?: number;
  name?: string;
  description?: string;
  srcSet?: BannerDTOSrcSet;
  url?: string;
}
