/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */

export interface BannerRequest {
  /**
   * @minLength 5
   * @maxLength 200
   */
  name: string;
  /**
   * @minLength 0
   * @maxLength 4000
   */
  description?: string;
  url: string;
  shopId?: number;
}
