/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { ImageDTO } from "./imageDTO";

export interface BookDisplayDTO {
  id?: number;
  slug?: string;
  title?: string;
  image?: ImageDTO;
  description?: string;
  price?: number;
  discount?: number;
  amount?: number;
  shopId?: number;
  shopName?: string;
  rating?: number;
  totalOrders?: number;
}
