/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export type BookLanguage = (typeof BookLanguage)[keyof typeof BookLanguage];

export const BookLanguage = {
  VN: "VN",
  EN: "EN",
  CN: "CN",
  JP: "JP",
} as const;
