/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { Image } from "./image";
import type { BookType } from "./bookType";
import type { BookLanguage } from "./bookLanguage";
import type { PublisherDTO } from "./publisherDTO";
import type { CategoryDTO } from "./categoryDTO";

export interface BookDTO {
  id?: number;
  slug?: string;
  image?: Image;
  previews?: Image[];
  price?: number;
  discount?: number;
  title?: string;
  description?: string;
  type?: BookType;
  author?: string;
  size?: string;
  pages?: number;
  date?: string;
  language?: BookLanguage;
  weight?: number;
  amount?: number;
  publisher?: PublisherDTO;
  category?: CategoryDTO;
  shopId?: number;
  shopName?: string;
}
