/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { BookDetailDTOSrcSet } from "./bookDetailDTOSrcSet";
import type { BookDetailDTOPreviewsSrcSetItem } from "./bookDetailDTOPreviewsSrcSetItem";
import type { BookType } from "./bookType";
import type { PublisherDTO } from "./publisherDTO";
import type { CategoryDTO } from "./categoryDTO";
import type { BookLanguage } from "./bookLanguage";
import type { ReviewsInfoDTO } from "./reviewsInfoDTO";

export interface BookDetailDTO {
  id?: number;
  slug?: string;
  srcSet?: BookDetailDTOSrcSet;
  previewsSrcSet?: BookDetailDTOPreviewsSrcSetItem[];
  price?: number;
  discount?: number;
  title?: string;
  description?: string;
  type?: BookType;
  author?: string;
  amount?: number;
  shopId?: number;
  shopName?: string;
  publisher?: PublisherDTO;
  category?: CategoryDTO;
  size?: string;
  pages?: number;
  date?: string;
  language?: BookLanguage;
  weight?: number;
  totalOrders?: number;
  reviewsInfo?: ReviewsInfoDTO;
}
