/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { BookType } from "./bookType";
import type { BookLanguage } from "./bookLanguage";

export interface BookRequest {
  /**
   * @minimum 1000
   * @maximum 10000000
   */
  price: number;
  /**
   * @minimum 0
   */
  discount?: number;
  /**
   * @minimum 1
   * @maximum 10000
   */
  amount: number;
  title: string;
  description: string;
  type: BookType;
  author: string;
  pubId: number;
  cateId: number;
  /** @minimum 1 */
  weight: number;
  size: string;
  /** @minimum 1 */
  pages: number;
  date?: string;
  language: BookLanguage;
  shopId: number;
  thumbnailId?: number;
  removeIds?: number[];
}
