/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { BookDisplayDTOSrcSet } from "./bookDisplayDTOSrcSet";

export interface BookDisplayDTO {
  id?: number;
  slug?: string;
  title?: string;
  srcSet?: BookDisplayDTOSrcSet;
  description?: string;
  price?: number;
  discount?: number;
  amount?: number;
  shopId?: number;
  shopName?: string;
  rating?: number;
  totalOrders?: number;
}
