/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface BookResponseDTO {
  id?: number;
  slug?: string;
  price?: number;
  discount?: number;
  title?: string;
}
