/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { BookDTOSrcSetItem } from "./bookDTOSrcSetItem";
import type { BookLanguage } from "./bookLanguage";
import type { BookType } from "./bookType";
import type { CategoryDTO } from "./categoryDTO";
import type { PublisherDTO } from "./publisherDTO";

export interface BookDTO {
  id?: number;
  slug?: string;
  srcSet?: BookDTOSrcSetItem[];
  imagePublicIds?: string[];
  price?: number;
  discount?: number;
  title?: string;
  description?: string;
  type?: BookType;
  author?: string;
  amount?: number;
  shopId?: number;
  shopName?: string;
  publisher?: PublisherDTO;
  category?: CategoryDTO;
  size?: string;
  pages?: number;
  date?: string;
  language?: BookLanguage;
  weight?: number;
  totalOrders?: number;
  rating?: number;
  totalRates?: number;
}
