/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { BookDetailDTOSrcSetItem } from "./bookDetailDTOSrcSetItem";
import type { BookLanguage } from "./bookLanguage";
import type { BookType } from "./bookType";
import type { CategoryDTO } from "./categoryDTO";
import type { PublisherDTO } from "./publisherDTO";
import type { ReviewsInfoDTO } from "./reviewsInfoDTO";

export interface BookDetailDTO {
  id?: number;
  slug?: string;
  srcSet?: BookDetailDTOSrcSetItem[];
  price?: number;
  discount?: number;
  title?: string;
  description?: string;
  type?: BookType;
  author?: string;
  amount?: number;
  shopId?: number;
  shopName?: string;
  publisher?: PublisherDTO;
  category?: CategoryDTO;
  length?: number;
  width?: number;
  height?: number;
  pages?: number;
  date?: string;
  language?: BookLanguage;
  weight?: number;
  totalOrders?: number;
  reviewsInfo?: ReviewsInfoDTO;
}
