/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { BookLanguage } from "./bookLanguage";
import type { BookType } from "./bookType";

export interface BookRequest {
  /**
   * @minimum 1000
   * @maximum 10000000
   */
  price: number;
  /** @minimum 0 */
  discount?: number;
  /**
   * @minimum 1
   * @maximum 10000
   */
  amount: number;
  title: string;
  description: string;
  type: BookType;
  author: string;
  pubId: number;
  cateId: number;
  /** @minimum 1 */
  weight: number;
  /** @minimum 1 */
  length: number;
  /** @minimum 1 */
  width: number;
  /** @minimum 1 */
  height: number;
  /** @minimum 1 */
  pages: number;
  date?: string;
  language: BookLanguage;
  shopId: number;
  thumbnailPublicId?: string;
  removePublicIds?: string[];
}
