/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export type BookType = (typeof BookType)[keyof typeof BookType];

export const BookType = {
  HARD_COVER: "HARD_COVER",
  SOFT_COVER: "SOFT_COVER",
  WOOD_COVER: "WOOD_COVER",
  SLIP_COVER: "SLIP_COVER",
  OTHERS: "OTHERS",
} as const;
