/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface CalculateItemDTO {
  price?: number;
  discount?: number;
  amount?: number;
  quantity?: number;
  id?: number;
  slug?: string;
  title?: string;
}
