/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { CouponDTO } from "./couponDTO";
import type { CalculateDetailDTO } from "./calculateDetailDTO";

export interface CalculateDTO {
  total?: number;
  productsTotal?: number;
  shippingFee?: number;
  totalDiscount?: number;
  dealDiscount?: number;
  couponDiscount?: number;
  shippingDiscount?: number;
  coupon?: CouponDTO;
  details?: CalculateDetailDTO[];
}
