/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { CouponDTO } from "./couponDTO";
import type { CalculateItemDTO } from "./calculateItemDTO";

export interface CalculateDetailDTO {
  shopId?: number;
  shopName?: string;
  totalPrice?: number;
  totalDiscount?: number;
  couponDiscount?: number;
  shippingFee?: number;
  shippingDiscount?: number;
  coupon?: CouponDTO;
  items?: CalculateItemDTO[];
}
