/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { AddressRequest } from "./addressRequest";
import type { CartDetailRequest } from "./cartDetailRequest";

export interface CalculateRequest {
  cart: CartDetailRequest[];
  coupon?: string;
  address?: AddressRequest;
}
