/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { CalculateItemDTO } from "./calculateItemDTO";
import type { CouponDTO } from "./couponDTO";

export interface CalculateDetailDTO {
  shopId?: number;
  shopName?: string;
  totalPrice?: number;
  totalDiscount?: number;
  couponDiscount?: number;
  shippingFee?: number;
  shippingDiscount?: number;
  coupon?: CouponDTO;
  items?: CalculateItemDTO[];
}
