/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { CalculateDetailDTO } from "./calculateDetailDTO";
import type { CouponDTO } from "./couponDTO";

export interface CalculateDTO {
  total?: number;
  productsTotal?: number;
  shippingFee?: number;
  totalDiscount?: number;
  dealDiscount?: number;
  couponDiscount?: number;
  shippingDiscount?: number;
  coupon?: CouponDTO;
  details?: CalculateDetailDTO[];
}
