/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */

export interface CalculateItemDTO {
  price?: number;
  discount?: number;
  amount?: number;
  quantity?: number;
  id?: number;
  slug?: string;
  title?: string;
}
