/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { CartDetailRequest } from "./cartDetailRequest";
import type { AddressRequest } from "./addressRequest";

export interface CalculateRequest {
  cart: CartDetailRequest[];
  coupon?: string;
  address?: AddressRequest;
}
