/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { ShippingType } from "./shippingType";
import type { CartItemRequest } from "./cartItemRequest";

export interface CartDetailRequest {
  shopId: number;
  coupon?: string;
  /**
   * @minLength 0
   * @maxLength 300
   */
  note?: string;
  shippingType: ShippingType;
  items: CartItemRequest[];
}
