/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { CartItemRequest } from "./cartItemRequest";

export interface CartDetailRequest {
  shopId: number;
  coupon?: string;
  /**
   * @minLength 0
   * @maxLength 300
   */
  note?: string;
  shippingType: number;
  items: CartItemRequest[];
}
