/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { CategoryDTO as __CategoryDTO } from "./categoryDTO";

export interface CategoryDTO {
  id?: number;
  slug?: string;
  name?: string;
  parentId?: number;
  parent?: __CategoryDTO;
  children?: CategoryDTO[];
}
