/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface CategoryRequest {
  /**
   * @minLength 1
   * @maxLength 50
   */
  name: string;
  parentId?: number;
  /**
   * @minLength 0
   * @maxLength 500
   */
  description?: string;
}
