/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { CategoryDTO } from "./categoryDTO";

export interface CategoryDetailDTO {
  id?: number;
  slug?: string;
  name?: string;
  description?: string;
  parentId?: number;
  parent?: CategoryDTO;
  children?: CategoryDTO[];
}
