/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */

export interface CategoryRequest {
  /**
   * @minLength 1
   * @maxLength 50
   */
  name: string;
  parentId?: number;
  /**
   * @minLength 0
   * @maxLength 500
   */
  description?: string;
}
