/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { CategoryDTO } from "./categoryDTO";

export interface CategoryDetailDTO {
  id?: number;
  slug?: string;
  name?: string;
  description?: string;
  parentId?: number;
  parent?: CategoryDTO;
  children?: CategoryDTO[];
}
