/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { CategoryDTO as __CategoryDTO } from "./categoryDTO";

export interface CategoryDTO {
  id?: number;
  slug?: string;
  name?: string;
  parentId?: number;
  parent?: __CategoryDTO;
  children?: CategoryDTO[];
}
