/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface ChangePassRequest {
  pass: string;
  /**
   * @minLength 8
   * @maxLength 24
   */
  newPass: string;
  /**
   * @minLength 8
   * @maxLength 24
   */
  newPassRe: string;
}
