/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */

export type ChartDTOData = { [key: string]: number };
