/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { OrderDTO } from "./orderDTO";
import type { PaymentStatus } from "./paymentStatus";
import type { PaymentType } from "./paymentType";

export interface CheckoutDetailDTO {
  id?: number;
  name?: string;
  phone?: string;
  address?: string;
  email?: string;
  orderedDate?: string;
  date?: string;
  total?: number;
  totalDiscount?: number;
  paymentType?: PaymentType;
  paymentStatus?: PaymentStatus;
  expiredAt?: string;
  details?: OrderDTO[];
}
