/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface ConfirmWebhookResponse {
  webhookUrl?: string;
  accountName?: string;
  accountNumber?: string;
  name?: string;
  shortName?: string;
}
