/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface Coupon {
  createdDate?: string;
  lastModifiedDate?: string;
  id?: number;
  code?: string;
  isUsable?: boolean;
  isUsed?: boolean;
}
