/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export type CouponCriteria = (typeof CouponCriteria)[keyof typeof CouponCriteria];

export const CouponCriteria = {
  QUANTITY: "QUANTITY",
  VALUE: "VALUE",
} as const;
