/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { CouponCriteria } from "./couponCriteria";
import type { CouponType } from "./couponType";

export interface CouponRequest {
  /**
   * @minLength 5
   * @maxLength 50
   */
  code: string;
  type: CouponType;
  criteria: CouponCriteria;
  /** @maximum 9999 */
  usage?: number;
  expireDate?: string;
  /** @minimum 0 */
  attribute: number;
  maxDiscount?: number;
  /** @exclusiveMinimum 0 */
  discount?: number;
  shopId?: number;
}
