/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { CouponType } from "./couponType";
import type { CouponCriteria } from "./couponCriteria";

export interface CouponRequest {
  /**
   * @minLength 5
   * @maxLength 50
   */
  code: string;
  type: CouponType;
  criteria: CouponCriteria;
  /** @maximum 9999 */
  usage?: number;
  expireDate?: string;
  /** @minimum 0 */
  attribute: number;
  maxDiscount?: number;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  discount?: number;
  shopId?: number;
}
