/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export type CouponType = (typeof CouponType)[keyof typeof CouponType];

export const CouponType = {
  SHIPPING: "SHIPPING",
  PRODUCT: "PRODUCT",
} as const;
