/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { CouponType } from "./couponType";
import type { CouponCriteria } from "./couponCriteria";

export interface CouponDTO {
  id?: number;
  code?: string;
  isUsable?: boolean;
  isUsed?: boolean;
  type?: CouponType;
  criteria?: CouponCriteria;
  discount?: number;
  maxDiscount?: number;
  attribute?: number;
  usage?: number;
  expDate?: string;
  shopId?: number;
  shopName?: string;
  shopImage?: string;
}
