/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { CouponCriteria } from "./couponCriteria";
import type { CouponType } from "./couponType";

export interface CouponDTO {
  id?: number;
  code?: string;
  isUsable?: boolean;
  isUsed?: boolean;
  type?: CouponType;
  criteria?: CouponCriteria;
  discount?: number;
  maxDiscount?: number;
  attribute?: number;
  usage?: number;
  expDate?: string;
  shopId?: number;
  shopName?: string;
  shopImage?: string;
}
