/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */

export type CouponCriteria = (typeof CouponCriteria)[keyof typeof CouponCriteria];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CouponCriteria = {
  QUANTITY: "QUANTITY",
  VALUE: "VALUE",
} as const;
