/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { PaymentLinkStatus } from "./paymentLinkStatus";

export interface CreatePaymentLinkResponse {
  bin?: string;
  accountNumber?: string;
  accountName?: string;
  amount?: number;
  description?: string;
  orderCode?: number;
  currency?: string;
  paymentLinkId?: string;
  status?: PaymentLinkStatus;
  expiredAt?: number;
  checkoutUrl?: string;
  qrCode?: string;
}
