/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { DistrictResponse } from "./districtResponse";

export interface DistrictsResponse {
  code?: number;
  message?: string;
  data?: DistrictResponse[];
}
