/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface DistrictItemResponse {
  DistrictID?: number;
  ProvinceID?: number;
  DistrictName?: string;
}
