/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { ExceptionResponseErrors } from "./exceptionResponseErrors";

export interface ExceptionResponse {
  status?: number;
  error?: string;
  errors?: ExceptionResponseErrors;
  message?: string;
}
