/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface Fee {
  CODFailedFee?: number;
  CODFee?: number;
  Coupon?: number;
  DeliverRemoteAreasFee?: number;
  DocumentReturn?: number;
  DoubleCheck?: number;
  Insurance?: number;
  MainService?: number;
  PickRemoteAreasFee?: number;
  R2S?: number;
  Return?: number;
  StationDO?: number;
  StationPU?: number;
  Total?: number;
}
