/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export type Gender = (typeof Gender)[keyof typeof Gender];

export const Gender = {
  MALE: "MALE",
  FEMALE: "FEMALE",
} as const;
