/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { GHNCreateStoreDataResponse } from "./gHNCreateStoreDataResponse";

export interface GHNCreateStoreResponse {
  code?: number;
  message?: string;
  data?: GHNCreateStoreDataResponse;
}
