/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface GHNCreateStoreRequest {
  name?: string;
  phone?: string;
  address?: string;
  district_id?: number;
  ward_code?: string;
}
