/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface GHNFeeRequest {
  length?: number;
  width?: number;
  height?: number;
  weight?: number;
  coupon?: string;
  service_type_id?: number;
  service_id?: number;
  from_district_id?: number;
  from_ward_code?: string;
  to_district_id?: number;
  to_ward_code?: string;
  insurance_value?: number;
  cod_failed_amount?: number;
  cod_value?: number;
}
