/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { GHNFeeDataResponse } from "./gHNFeeDataResponse";

export interface GHNFeeResponse {
  code?: number;
  message?: string;
  data?: GHNFeeDataResponse;
}
