/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface GHNGetStoresRequest {
  offset?: number;
  limit?: number;
  client_phone?: string;
}
