/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { GHNGetStoresDataResponse } from "./gHNGetStoresDataResponse";

export interface GHNGetStoresResponse {
  code?: number;
  message?: string;
  data?: GHNGetStoresDataResponse;
}
