/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { GHNStoreResponse } from "./gHNStoreResponse";

export interface GHNGetStoresDataResponse {
  shops?: GHNStoreResponse[];
  last_offset?: number;
}
