/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { Fee } from "./fee";

export interface GHNOrderStatusWebhookPayload {
  CODAmount?: number;
  ClientOrderCode?: string;
  ConvertedWeight?: number;
  Description?: string;
  Fee?: Fee;
  Height?: number;
  IsPartialReturn?: boolean;
  Length?: number;
  OrderCode?: string;
  PartialReturnCode?: string;
  PaymentType?: number;
  Reason?: string;
  ReasonCode?: string;
  ShopID?: number;
  Status?: string;
  Time?: string;
  TotalFee?: number;
  Type?: string;
  Warehouse?: string;
  Weight?: number;
  Width?: number;
}
