/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { Log } from "./log";

export interface GHNOrderDetail {
  status?: string;
  leadtime?: string;
  log?: Log[];
  order_code?: string;
  client_order_code?: string;
  created_date?: string;
}
