/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface GHNStoreResponse {
  name?: string;
  phone?: string;
  address?: string;
  status?: number;
  _id?: number;
  ward_code?: string;
  district_id?: number;
  client_id?: number;
}
