/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface Image {
  id?: number;
  name?: string;
  publicId?: string;
  url?: string;
  type?: string;
}
