/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */

export interface Image {
  id?: number;
  name?: string;
  publicId?: string;
  url?: string;
  type?: string;
}
