/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface Invoice {
  invoiceId?: string;
  invoiceNumber?: string;
  issuedTimestamp?: number;
  issuedDatetime?: string;
  transactionId?: string;
  reservationCode?: string;
  codeOfTax?: string;
}
