/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { OrderStatus } from "./orderStatus";

export interface OrderSummaryDTO {
  id?: number;
  name?: string;
  date?: string;
  status?: OrderStatus;
  totalPrice?: number;
  totalItems?: number;
}
