/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { OrderItemDTO } from "./orderItemDTO";
import type { OrderStatus } from "./orderStatus";

export interface OrderDTO {
  id?: number;
  orderId?: number;
  shopId?: number;
  shopName?: string;
  totalPrice?: number;
  totalDiscount?: number;
  shippingFee?: number;
  shippingDiscount?: number;
  serviceTypeId?: number;
  serviceId?: number;
  serviceName?: string;
  note?: string;
  totalItems?: number;
  date?: string;
  status?: OrderStatus;
  items?: OrderItemDTO[];
}
