/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { OrderItemDTO } from "./orderItemDTO";
import type { OrderStatus } from "./orderStatus";

export interface OrderDTO {
  id?: number;
  orderId?: number;
  orderCode?: string;
  clientOrderCode?: string;
  shopId?: number;
  ghnShopId?: number;
  shopName?: string;
  totalPrice?: number;
  totalDiscount?: number;
  shippingFee?: number;
  shippingDiscount?: number;
  shippingType?: number;
  weightGrams?: number;
  lengthCm?: number;
  widthCm?: number;
  heightCm?: number;
  note?: string;
  totalItems?: number;
  date?: string;
  status?: OrderStatus;
  items?: OrderItemDTO[];
}
