/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { ShippingType } from "./shippingType";
import type { PaymentType } from "./paymentType";
import type { OrderStatus } from "./orderStatus";
import type { PaymentStatus } from "./paymentStatus";
import type { OrderItemDTO } from "./orderItemDTO";

export interface OrderDetailDTO {
  orderId?: number;
  name?: string;
  phone?: string;
  address?: string;
  note?: string;
  orderedDate?: string;
  date?: string;
  id?: number;
  shopId?: number;
  shopName?: string;
  totalPrice?: number;
  totalDiscount?: number;
  shippingFee?: number;
  shippingDiscount?: number;
  shippingType?: ShippingType;
  paymentType?: PaymentType;
  status?: OrderStatus;
  paymentStatus?: PaymentStatus;
  items?: OrderItemDTO[];
}
