/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { OrderItemDTO } from "./orderItemDTO";
import type { OrderStatus } from "./orderStatus";
import type { PaymentStatus } from "./paymentStatus";
import type { PaymentType } from "./paymentType";

export interface OrderDetailDTO {
  orderId?: number;
  orderCode?: string;
  name?: string;
  phone?: string;
  address?: string;
  note?: string;
  orderedDate?: string;
  date?: string;
  id?: number;
  shopId?: number;
  shopName?: string;
  totalPrice?: number;
  totalDiscount?: number;
  shippingFee?: number;
  shippingDiscount?: number;
  shippingType?: number;
  paymentType?: PaymentType;
  status?: OrderStatus;
  paymentStatus?: PaymentStatus;
  items?: OrderItemDTO[];
}
