/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { CartDetailRequest } from "./cartDetailRequest";
import type { PaymentType } from "./paymentType";
import type { AddressRequest } from "./addressRequest";

export interface OrderRequest {
  cart: CartDetailRequest[];
  coupon?: string;
  paymentMethod: PaymentType;
  address: AddressRequest;
}
