/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface OrderItemDTO {
  id?: number;
  price?: number;
  discount?: number;
  quantity?: number;
  bookId?: number;
  bookSlug?: string;
  image?: string;
  bookTitle?: string;
}
