/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */

export interface OrderItemDTO {
  id?: number;
  price?: number;
  discount?: number;
  quantity?: number;
  bookId?: number;
  bookSlug?: string;
  image?: string;
  bookTitle?: string;
}
