/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { ShippingType } from "./shippingType";
import type { OrderStatus } from "./orderStatus";
import type { OrderItemDTO } from "./orderItemDTO";

export interface OrderDTO {
  id?: number;
  orderId?: number;
  shopId?: number;
  shopName?: string;
  totalPrice?: number;
  totalDiscount?: number;
  shippingFee?: number;
  shippingDiscount?: number;
  shippingType?: ShippingType;
  note?: string;
  totalItems?: number;
  date?: string;
  status?: OrderStatus;
  items?: OrderItemDTO[];
}
