/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderStatus = {
  PENDING_PAYMENT: "PENDING_PAYMENT",
  PENDING: "PENDING",
  SHIPPING: "SHIPPING",
  COMPLETED: "COMPLETED",
  CANCELED: "CANCELED",
  PENDING_RETURN: "PENDING_RETURN",
  PENDING_REFUND: "PENDING_REFUND",
  REFUNDED: "REFUNDED",
} as const;
