/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { AddressRequest } from "./addressRequest";
import type { CartDetailRequest } from "./cartDetailRequest";
import type { PaymentType } from "./paymentType";

export interface OrderRequest {
  cart: CartDetailRequest[];
  coupon?: string;
  paymentMethod: PaymentType;
  address: AddressRequest;
}
