/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { ReceiptDTO } from "./receiptDTO";

export interface PagingResponseReceiptDTO {
  content?: ReceiptDTO[];
  totalPages?: number;
  totalElements?: number;
  size?: number;
  page?: number;
  empty?: boolean;
}
