/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { ReceiptSummaryDTO } from "./receiptSummaryDTO";

export interface PagingResponseReceiptSummaryDTO {
  content?: ReceiptSummaryDTO[];
  totalPages?: number;
  totalElements?: number;
  size?: number;
  page?: number;
  empty?: boolean;
}
