/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { ShopDisplayDTO } from "./shopDisplayDTO";

export interface PagingResponseShopDisplayDTO {
  content?: ShopDisplayDTO[];
  totalPages?: number;
  totalElements?: number;
  size?: number;
  page?: number;
  empty?: boolean;
}
