/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { PublisherDTO } from "./publisherDTO";

export interface PagingResponsePublisherDTO {
  content?: PublisherDTO[];
  totalPages?: number;
  totalElements?: number;
  size?: number;
  page?: number;
  empty?: boolean;
}
