/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { AccountDTO } from "./accountDTO";

export interface PagingResponseAccountDTO {
  content?: AccountDTO[];
  totalPages?: number;
  totalElements?: number;
  size?: number;
  page?: number;
  empty?: boolean;
}
