/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { OrderSummaryDTO } from "./orderSummaryDTO";

export interface PagingResponseOrderSummaryDTO {
  content?: OrderSummaryDTO[];
  totalPages?: number;
  totalElements?: number;
  size?: number;
  page?: number;
  empty?: boolean;
}
