/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { BookDisplayDTO } from "./bookDisplayDTO";

export interface PagingResponseBookDisplayDTO {
  content?: BookDisplayDTO[];
  totalPages?: number;
  totalElements?: number;
  size?: number;
  page?: number;
  empty?: boolean;
}
