/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { CategoryDTO } from "./categoryDTO";

export interface PagingResponseCategoryDTO {
  content?: CategoryDTO[];
  totalPages?: number;
  totalElements?: number;
  size?: number;
  page?: number;
  empty?: boolean;
}
