/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { PaymentStatus } from "./paymentStatus";
import type { PaymentType } from "./paymentType";

export interface PaymentInfo {
  id?: number;
  paymentType?: PaymentType;
  status?: PaymentStatus;
  checkoutUrl?: string;
  amount?: number;
  description?: string;
  expiredAt?: string;
}
