/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { Transaction } from "./transaction";

export interface PaymentLinkData {
  id?: string;
  orderCode?: number;
  amount?: number;
  amountPaid?: number;
  amountRemaining?: number;
  status?: string;
  createdAt?: string;
  transactions?: Transaction[];
  cancellationReason?: string;
  canceledAt?: string;
}
