/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { PaymentType } from "./paymentType";
import type { PaymentStatus } from "./paymentStatus";

export interface PaymentInfo {
  id?: number;
  paymentType?: PaymentType;
  status?: PaymentStatus;
  checkoutUrl?: string;
  amount?: number;
  description?: string;
  expiredAt?: string;
}
