/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { PaymentLinkStatus } from "./paymentLinkStatus";
import type { Transaction } from "./transaction";

export interface PaymentLink {
  id?: string;
  orderCode?: number;
  amount?: number;
  amountPaid?: number;
  amountRemaining?: number;
  status?: PaymentLinkStatus;
  createdAt?: string;
  transactions?: Transaction[];
  cancellationReason?: string;
  canceledAt?: string;
}
