/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export type PaymentLinkStatus = (typeof PaymentLinkStatus)[keyof typeof PaymentLinkStatus];

export const PaymentLinkStatus = {
  PENDING: "PENDING",
  CANCELLED: "CANCELLED",
  UNDERPAID: "UNDERPAID",
  PAID: "PAID",
  EXPIRED: "EXPIRED",
  PROCESSING: "PROCESSING",
  FAILED: "FAILED",
} as const;
