/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export type PaymentType = (typeof PaymentType)[keyof typeof PaymentType];

export const PaymentType = {
  CASH: "CASH",
  ONLINE_PAYMENT: "ONLINE_PAYMENT",
} as const;
