/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface PreviewCategoryDTO {
  id?: number;
  slug?: string;
  parentId?: number;
  name?: string;
  image?: string;
}
