/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { Privilege } from "./privilege";

export interface PrivilegeGroup {
  id?: number;
  groupName?: string;
  groupPrivileges?: Privilege[];
}
