/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { Privilege } from "./privilege";

export interface PrivilegeGroup {
  id?: number;
  groupName?: string;
  groupPrivileges?: Privilege[];
}
