/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { PrivilegeType } from "./privilegeType";

export interface Privilege {
  id?: number;
  label?: string;
  privilegeType?: PrivilegeType;
}
