/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { PrivilegeType } from "./privilegeType";

export interface Privilege {
  id?: number;
  label?: string;
  privilegeType?: PrivilegeType;
}
