/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { Gender } from "./gender";

export interface ProfileRequest {
  /**
   * @minLength 0
   * @maxLength 150
   */
  name?: string;
  /** @pattern \(?([0-9]{3})\)?([ .-]?)([0-9]{3})\2([0-9]{3}) */
  phone?: string;
  dob?: string;
  gender?: Gender;
  removeImage?: boolean;
}
