/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { Gender } from "./gender";

export interface ProfileDTO {
  image?: string;
  name?: string;
  email?: string;
  phone?: string;
  gender?: Gender;
  dob?: string;
  joinedDate?: string;
  totalFollows?: number;
  totalReviews?: number;
}
