/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { ProvinceResponse } from "./provinceResponse";

export interface ProvincesResponse {
  code?: number;
  message?: string;
  data?: ProvinceResponse[];
}
