/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface ProvinceResponse {
  ProvinceID?: number;
  ProvinceName?: string;
  Code?: string;
}
