/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface PublisherRequest {
  /**
   * @minLength 1
   * @maxLength 50
   */
  name: string;
}
