/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */

export interface ReceiptSummaryDTO {
  id?: number;
  image?: string;
  name?: string;
  date?: string;
  totalPrice?: number;
  totalItems?: number;
}
