/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { OrderDTO } from "./orderDTO";

export interface ReceiptDTO {
  id?: number;
  email?: string;
  name?: string;
  image?: string;
  phone?: string;
  address?: string;
  detail?: string;
  date?: string;
  total?: number;
  totalDiscount?: number;
  username?: string;
  details?: OrderDTO[];
}
