/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { PaymentType } from "./paymentType";
import type { PaymentStatus } from "./paymentStatus";
import type { OrderDTO } from "./orderDTO";

export interface ReceiptDetailDTO {
  id?: number;
  name?: string;
  phone?: string;
  address?: string;
  email?: string;
  orderedDate?: string;
  date?: string;
  total?: number;
  totalDiscount?: number;
  paymentType?: PaymentType;
  paymentStatus?: PaymentStatus;
  expiredAt?: string;
  details?: OrderDTO[];
}
