/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { OrderDTO } from "./orderDTO";

export interface ReceiptDTO {
  id?: number;
  email?: string;
  name?: string;
  image?: string;
  phone?: string;
  address?: string;
  date?: string;
  total?: number;
  totalDiscount?: number;
  username?: string;
  details?: OrderDTO[];
}
