/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface RegisterRequest {
  /**
   * @minLength 4
   * @maxLength 24
   */
  username: string;
  /**
   * @minLength 8
   * @maxLength 24
   */
  pass: string;
  email: string;
}
