/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */

export interface RegisterRequest {
  /**
   * @minLength 4
   * @maxLength 24
   */
  username: string;
  /**
   * @minLength 8
   * @maxLength 24
   */
  pass: string;
  email: string;
}
