/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */

export interface ResetPassRequest {
  /**
   * @minLength 8
   * @maxLength 24
   */
  newPass: string;
  /**
   * @minLength 8
   * @maxLength 24
   */
  newPassRe: string;
}
