/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */

export interface ReviewRequest {
  /**
   * @minLength 50
   * @maxLength 2147483647
   */
  content: string;
  rating: number;
}
