/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface Review {
  createdDate?: string;
  lastModifiedDate?: string;
  id?: number;
  rating?: number;
  hidden?: boolean;
  rcontent?: string;
}
