/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface ReviewRequest {
  /**
   * @minLength 50
   * @maxLength 2147483647
   */
  content: string;
  rating: number;
}
