/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface ReviewDTO {
  id?: number;
  content?: string;
  rating?: number;
  date?: string;
  updatedDate?: string;
  userId?: number;
  username?: string;
  userImage?: string;
  bookId?: number;
  bookTitle?: string;
  bookSlug?: string;
}
