/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */

export interface ReviewDTO {
  id?: number;
  content?: string;
  rating?: number;
  date?: string;
  updatedDate?: string;
  userId?: number;
  username?: string;
  userImage?: string;
  bookId?: number;
  bookTitle?: string;
  bookSlug?: string;
}
