/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { UserRole } from "./userRole";
import type { Privilege } from "./privilege";

export interface Role {
  label?: string;
  roleName?: UserRole;
  privileges?: Privilege[];
}
