/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { Privilege } from "./privilege";
import type { UserRole } from "./userRole";

export interface Role {
  label?: string;
  roleName?: UserRole;
  privileges?: Privilege[];
}
