/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export type ShippingType = (typeof ShippingType)[keyof typeof ShippingType];

export const ShippingType = {
  ECONOMY: "ECONOMY",
  STANDARD: "STANDARD",
  EXPRESS: "EXPRESS",
} as const;
