/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */

export interface ShopDisplayDTO {
  ownerId?: number;
  id?: number;
  name?: string;
  image?: string;
  joinedDate?: string;
  totalReviews?: number;
  totalProducts?: number;
  totalFollowers?: number;
  followed?: boolean;
}
