/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { AddressRequest } from "./addressRequest";

export interface ShopRequest {
  /**
   * @minLength 0
   * @maxLength 250
   */
  name?: string;
  /**
   * @minLength 0
   * @maxLength 500
   */
  description?: string;
  image?: string;
  addressRequest: AddressRequest;
}
