/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface ShopDisplayDTO {
  ownerId?: number;
  id?: number;
  name?: string;
  verified?: boolean;
  image?: string;
  joinedDate?: string;
  totalReviews?: number;
  totalProducts?: number;
  totalFollowers?: number;
  followed?: boolean;
}
