/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface ShopDTO {
  username?: string;
  ownerId?: number;
  id?: number;
  name?: string;
  verified?: boolean;
  image?: string;
  sales?: number;
  totalOrders?: number;
  totalProducts?: number;
  canceledRate?: number;
  totalReviews?: number;
  totalFollowers?: number;
  joinedDate?: string;
}
