/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { AddressRequest } from "./addressRequest";

export interface ShopRequest {
  /**
   * @minLength 0
   * @maxLength 250
   */
  name?: string;
  /**
   * @minLength 0
   * @maxLength 500
   */
  description?: string;
  image?: string;
  addressRequest: AddressRequest;
}
