/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */

export interface ShopDTO {
  username?: string;
  ownerId?: number;
  id?: number;
  name?: string;
  image?: string;
  sales?: number;
  totalSold?: number;
  totalFollowers?: number;
  joinedDate?: string;
}
