/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface Shop {
  createdDate?: string;
  lastModifiedDate?: string;
  name?: string;
  description?: string;
  verified?: boolean;
}
