/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { AddressDTO } from "./addressDTO";

export interface ShopDisplayDetailDTO {
  username?: string;
  ownerId?: number;
  id?: number;
  name?: string;
  description?: string;
  image?: string;
  address?: AddressDTO;
  totalSold?: number;
  canceledRate?: number;
  totalProducts?: number;
  rating?: number;
  totalReviews?: number;
  totalFollowers?: number;
  joinedDate?: string;
  followed?: boolean;
}
