/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export interface Transaction {
  reference?: string;
  amount?: number;
  accountNumber?: string;
  description?: string;
  transactionDateTime?: string;
  virtualAccountName?: string;
  virtualAccountNumber?: string;
  counterAccountBankId?: string;
  counterAccountBankName?: string;
  counterAccountName?: string;
  counterAccountNumber?: string;
}
