/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */

export type UserRole = (typeof UserRole)[keyof typeof UserRole];

export const UserRole = {
  ROLE_USER: "ROLE_USER",
  ROLE_SELLER: "ROLE_SELLER",
  ROLE_ADMIN: "ROLE_ADMIN",
  ROLE_GUEST: "ROLE_GUEST",
} as const;
