/**
 * Generated by Orval
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 */
import type { WardResponse } from "./wardResponse";

export interface WardsResponse {
  code?: number;
  message?: string;
  data?: WardResponse[];
}
