/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI specification - RING-Bookstore
 * OpenAPI documentation.
 * OpenAPI spec version: 2.0
 */
import type { WebhookData } from "./webhookData";

export interface Webhook {
  code?: string;
  desc?: string;
  success?: boolean;
  data?: WebhookData;
  signature?: string;
}
