# ===============================
# Production
# ===============================
springdoc.api-docs.enabled=false
server.port=${PORT}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN

# ===============================
# Email
# ===============================
spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}

# ===============================
# PayOS
# ===============================
payos.log-level=NONE

# ===============================
# Cloudflare Turnstile
# ===============================
cloudflare.turnstile.secret=${TURNSTILE_SECRET_KEY}