# Enable forward headers filters
server.forward-headers-strategy=framework

# Localization
spring.messages.encoding=UTF-8
spring.messages.basename=messages
spring.messages.fallback-to-system-locale=false

# Enable gzip compression
server.compression.enabled=true
server.compression.min-response-size=2048
server.compression.mime-types=text/html,text/xml,text/plain,text/css,application/json,image/jpeg

# Exclude null values in json response
spring.jackson.default-property-inclusion=NON_NULL

# ===============================
# DATABASE
# ===============================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JPA / HIBERNATE
# ===============================
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.order_by.default_null_ordering=last

# ===============================
# Redis
# ===============================
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.cache.type=redis

# ===============================
# Security
# ===============================
application.security.jwt.cookie-domain=${COOKIE_DOMAIN}
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.secret-refresh-key=${JWT_SECRET_REFRESH_KEY}
application.security.jwt.token-expiration=1800000
application.security.jwt.refresh-token-expiration=604800000
server.servlet.session.cookie.same-site=none
allowed.origins=http://localhost:3000,http://localhost:3001,http://localhost:5173,http://localhost:4173

# ===============================
# Image
# ===============================
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# ===============================
# Email
# ===============================
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.sender=RING!-Bookstore <ring@ringdoraz.io.vn>

# ===============================
# Recaptcha
# ===============================
google.recaptcha.secret=${RECAPTCHA_SECRET_KEY}
google.recaptcha.v3-secret=${RECAPTCHA_V3_SECRET_KEY}
google.recaptcha.url=https://www.google.com/recaptcha/api/siteverify
google.recaptcha.threshold=0.3
google.recaptcha.suspicious=0.6

# ===============================
# Cloudinary
# ===============================
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# ===============================
# PayOS
# ===============================
payos.client_id=${PAYOS_CLIENT_ID}
payos.api_key=${PAYOS_API_KEY}
payos.checksum_key=${PAYOS_CHECKSUM_KEY}

# ===============================
# Other
# ===============================
ring.client-url=${CLIENT_URL}
ring.dashboard-url=${DASHBOARD_URL}
ring.openapi.prod-url=${PROD_URL}