# Enable forward headers filters
server.forward-headers-strategy=framework

# Localization
spring.messages.encoding=UTF-8
spring.messages.basename=messages
spring.messages.fallback-to-system-locale=false

# Enable gzip compression
server.compression.enabled=true
server.compression.min-response-size=2048
server.compression.mime-types=text/html,text/xml,text/plain,text/css,application/json,image/jpeg

# Exclude null values in json response
spring.jackson.default-property-inclusion=NON_NULL

# ===============================
# DATABASE
# ===============================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.order_by.default_null_ordering=last

# ===============================
# Redis
# ===============================
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.cache.type=redis
spring.data.redis.repositories.enabled = false

# ===============================
# Security
# ===============================
application.security.jwt.cookie-domain=${COOKIE_DOMAIN}
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.secret-refresh-key=${JWT_SECRET_REFRESH_KEY}
application.security.jwt.token-expiration=1800000
application.security.jwt.refresh-token-expiration=604800
server.servlet.session.cookie.same-site=none
allowed.origins=http://localhost:3000,http://localhost:3001,http://localhost:5173,http://localhost:4173

# ===============================
# Image
# ===============================
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# ===============================
# Email
# ===============================
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.sender=RING!-Bookstore <ring@ringdoraz.io.vn>

# ===============================
# Cloudflare Turnstile
# ===============================
cloudflare.turnstile.url=https://challenges.cloudflare.com/turnstile/v0/siteverify

# ===============================
# Cloudinary
# ===============================
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# ===============================
# PayOS
# ===============================
payos.client-id=${PAYOS_CLIENT_ID}
payos.api-key=${PAYOS_API_KEY}
payos.checksum-key=${PAYOS_CHECKSUM_KEY}

# ===============================
# GHN
# ===============================
ghn.api.token=${GHN_API_TOKEN}
ghn.api.shop-id=${GHN_SHOP_ID}
ghn.default.service-type-id=2
ghn.default.weight-grams=500
ghn.default.length-cm=20
ghn.default.width-cm=15
ghn.default.height-cm=5
ghn.default.fallback-fee=20000
ghn.api.url=${GHN_API_URL} 

# ===============================
# Other
# ===============================
ring.client-url=${CLIENT_URL}
ring.dashboard-url=${DASHBOARD_URL}
ring.openapi.prod-url=${PROD_URL}